export const ADD_NOTE_REQUEST = 'ADD_NOTE_REQUEST'
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS'
export const ADD_NOTE_FAILURE = 'ADD_NOTE_FAILURE'

export const LOGIN_FACEBOOK_REQUEST = 'LOGIN_FACEBOOK_REQUEST'
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS'
export const LOGIN_FACEBOOK_FAILURE = 'LOGIN_FACEBOOK_FAILURE'
export const LOGIN_FACEBOOK_CANCEL = 'LOGIN_FACEBOOK_CANCEL'

export const LOGIN_FIREBASE_REQUEST = 'LOGIN_FIREBASE_REQUEST'
export const LOGIN_FIREBASE_SUCCESS = 'LOGIN_FIREBASE_SUCCESS'
export const LOGIN_FIREBASE_FAILURE = 'LOGIN_FIREBASE_FAILURE'
