# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'mobileChallenge' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobileChallenge

  target 'mobileChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
# Required by RNFirebase
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
